version: '3'

# Spins up app dependencies and exposes them, for local dev environment.
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./.mongo-volume:/data/db
