version: '3'

name: next-dashboard-dev

# Spins up app dependencies and exposes them, for local dev environment.
services:
  mongo:
    container_name: dev-mongo
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./.mongo-volume-dev:/data/db
