version: "3"

name: next-dashboard-test

# Spins up and connects the app and all needed dependencies, populates test data and runs tests.
services:
  mongo:
    container_name: test-mongo
    image: mongo:6.0
    networks:
      - test_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-app
    ports:
      - ${APP_PORT}:3000
    environment:
      API_DATABASE_URI: mongodb://mongo:27017/test-next-dashboard
      API_LOG_LEVEL: ${API_LOG_LEVEL}
      JOBS_DATABASE_URI: mongodb://mongo:27017/test-next-dashboard
      JOBS_DATABASE_COLLECTION: ${JOBS_DATABASE_COLLECTION}
    depends_on:
      - mongo
    networks:
      - test_network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test-runner
    container_name: test-runner
    environment:
      TEST_APP_URI: app:3000
    depends_on:
      - app
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
