version: "3"

name: next-dashboard

# Spins up and connects the app and all needed dependencies.
services:
  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    volumes:
      - ./.mongo-volume:/data/db
    networks:
      - app_network
    logging:
      driver: none

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - ${APP_PORT}:3000
    environment:
      API_DATABASE_URI: mongodb://mongo:27017/next-dashboard
      API_LOG_LEVEL: ${API_LOG_LEVEL}
      JOBS_DATABASE_URI: mongodb://mongo:27017/next-dashboard
      JOBS_DATABASE_COLLECTION: ${JOBS_DATABASE_COLLECTION}
    depends_on:
      - mongo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
