name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy env
        working-directory: ./
        run: cp .env.test .env
      - name: Run tests
        working-directory: ./
        run: docker compose -f docker-compose.test.yml up --exit-code-from test-runner --build
